## Prepare data

Our goal is to get a small sample of the dataset to work with that is good enough to iterate on. A small sample makes it faster to iterate, hence enable easier debugging. If we can not make our model work on a reasonably small dataset then it's not likely to work on bigger one either.

We define a sufficiently small training dataset as:
- **Richness**: Every user should have at least 5 interactions and each item should have at least 10 interactions
- **Enough samples**: There should be at least 1000 users in the training dataset and about 1000 interactions in the validation set

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys
from functools import partial

import numpy as np
import plotly.express as px
from loguru import logger
from pydantic import BaseModel, model_validator
from load_dotenv import load_dotenv
import pandas as pd

from sqlalchemy import create_engine
from feast import FeatureStore

sys.path.insert(0, "..")

from src.visualization.setup import FSDSColors
from src.utils.split_time_based import train_test_split_timebased
_ = load_dotenv(override=True)

## Controler

In [4]:
class Args(BaseModel):
    run_name: str = "003-prep-data"
    testing: bool = False
    notebook_persist_dp: str = None
    random_seed: int = 41

    user_col: str = "customer_id"
    item_col: str = "article_id"
    interaction_col: str = "price"
    timestamp_col: str = "t_dat"

    sample_users: int = 1000
    min_user_interactions: int = 5
    min_item_interactions: int = 10

    val_num_days: int = 15
    test_num_days: int = 15

    feast_store_url: str = "../feature-pipeline/feature_store/staging"
    feast_data_source: str = "user_item_interactions"
    feast_service: str = "user_item_interactions_v1"

    # Database credentials
    user: str = None
    password: str = None
    db: str = None
    host: str = None
    port: int = None

    @model_validator(mode="before")
    def load_env_vars(cls, values):
        # Load environment variables if not explicitly set
        values["user"] = values.get("user") or os.getenv("POSTGRES_USER")
        values["password"] = values.get("password") or os.getenv("POSTGRES_PASSWORD")
        values["db"] = values.get("db") or os.getenv("POSTGRES_DB")
        values["host"] = values.get("host") or os.getenv("POSTGRES_HOST")
        values["port"] = values.get("port") or os.getenv("POSTGRES_PORT")
        return values

    def init(self):
        self.notebook_persist_dp = os.path.abspath(f"../data/interim")
        if not self.testing:
            os.makedirs(self.notebook_persist_dp, exist_ok=True)

        return self


args = Args().init()

print(args.model_dump_json(indent=2))

{
  "run_name": "003-prep-data",
  "testing": false,
  "notebook_persist_dp": "/home/dinhln/Desktop/MLOPS/recsys/HM-ScalableRecs/data/interim",
  "random_seed": 41,
  "user_col": "customer_id",
  "item_col": "article_id",
  "interaction_col": "price",
  "timestamp_col": "t_dat",
  "sample_users": 1000,
  "min_user_interactions": 5,
  "min_item_interactions": 10,
  "val_num_days": 15,
  "test_num_days": 15,
  "feast_store_url": "../feature-pipeline/feature_store/staging",
  "feast_data_source": "user_item_interactions",
  "feast_service": "user_item_interactions_v1",
  "user": "lastfirstkiss",
  "password": "nightchange",
  "db": "hm-recsys",
  "host": "localhost",
  "port": 5432
}

## Load data from a specific period in order to train the model

In notebook 002-simulate-oltp, we can see that the time period from March 2020 to Sep 2020 is the good choice. There are active interactions between users and items in this period and wen can keep the recency. So, we will load data from this period to train the model.

In [6]:
# Get interaction from March 2020 to the end of the data
connection_string = f"postgresql://{args.user}:{args.password}@{args.host}:{args.port}/{args.db}"
engine = create_engine(connection_string)
query = f"""
SELECT {args.user_col}, {args.timestamp_col} FROM {os.getenv("POSTGRES_FEATURE_STORE_OFFLINE_SCHEMA")}.transactions
WHERE {args.timestamp_col} >= '2020-03-01'
"""
entity_df = pd.read_sql(query, engine)
entity_df = entity_df.drop_duplicates()

In [7]:
entity_df.head()

                                         customer_id      t_dat
0  0000423b00ade91418cceaf3b26c6af3dd342b51fd051e... 2020-03-01
1  0008968c0d451dbc5a9968da03196fe20051965edde741... 2020-03-01
2  001127bffdda108579e6cb16080440e89bf1250a776c6e... 2020-03-01
4  00117f79ce61af038e143ee26448e8401fdbff51f48d5a... 2020-03-01
7  00227494dd4e87da02bb1ab4afc38f13f2e11c6517b1bb... 2020-03-01

In [11]:
from datetime import datetime
store = FeatureStore(repo_path= args.feast_store_url)
entity_df = pd.DataFrame.from_dict(
    {
        # entity's join key -> entity values
        "customer_id": list(entity_df[args.user_col]),
        # "event_timestamp" (reserved key) -> timestamps
        "event_timestamp": list(entity_df[args.timestamp_col])
    }
)

raw_df = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "user_item_interactions:article_id",
    ],
).to_df()

In [12]:
raw_df.head()

,customer_id,event_timestamp,article_id
0,02ed8f03830a333f464ba3f60bd3b983fde01b63c85fb1...,2020-03-01,824821002
1,02ed8f03830a333f464ba3f60bd3b983fde01b63c85fb1...,2020-03-01,764895001
2,02fe78a5c821bcf439d16e81f9e3472640b079fe6a9b14...,2020-03-01,719530004
3,02fe78a5c821bcf439d16e81f9e3472640b079fe6a9b14...,2020-03-01,882840002
4,02fe78a5c821bcf439d16e81f9e3472640b079fe6a9b14...,2020-03-01,871417001

## Sampling data

Just randomly get X users will not guarantee that the output dataset would qualify the condition of **richness**. Instead we take an iterative approach where we gradually drop random users from the dataset while keeping an eye on the conditions and our sampling target.

In [14]:
def remove_random_users(df, k=10):
    users = df[args.user_col].unique()
    np.random.seed(args.random_seed)
    to_remove_users = np.random.choice(users, size=k, replace=False)
    return df.loc[lambda df: ~df[args.user_col].isin(to_remove_users)]


def get_unqualified(df, col: str, threshold: int):
    unqualified = df.groupby(col).size().loc[lambda s: s < threshold].index
    return unqualified


get_unqualified_users = partial(
    get_unqualified, col=args.user_col, threshold=args.min_user_interactions
)
get_unqualified_items = partial(
    get_unqualified, col=args.item_col, threshold=args.min_item_interactions
)

In [15]:
buffer_perc = 0.2
perc_users_removed_each_round = 0.01
debug = True
keep_random_removing = True
r = 1

sample_df = raw_df.copy()

while keep_random_removing:
    num_users_removed_each_round = int(
        perc_users_removed_each_round * sample_df[args.user_col].nunique()
    )
    print(
        f"\n\nRandomly removing {num_users_removed_each_round} users - Round {r} started"
    )
    new_sample_df = remove_random_users(sample_df, k=num_users_removed_each_round)

    keep_removing = True
    i = 1

    while keep_removing:
        if debug:
            logger.info(f"Sampling round {i} started")
        keep_removing = False
        uu = get_unqualified_users(new_sample_df)
        if debug:
            logger.info(f"{len(uu)=}")
        if len(uu):
            new_sample_df = new_sample_df.loc[lambda df: ~df[args.user_col].isin(uu)]
            if debug:
                logger.info(f"After removing uu: {len(new_sample_df)=}")
            assert len(get_unqualified_users(new_sample_df)) == 0
            keep_removing = True
        ui = get_unqualified_items(new_sample_df)
        if debug:
            logger.info(f"{len(ui)=}")
        if len(ui):
            new_sample_df = new_sample_df.loc[lambda df: ~df[args.item_col].isin(ui)]
            if debug:
                logger.info(f"After removing ui: {len(new_sample_df)=}")
            assert len(get_unqualified_items(new_sample_df)) == 0
            keep_removing = True
        i += 1

    sample_users = sample_df[args.user_col].unique()
    sample_items = sample_df[args.item_col].unique()
    num_users = len(sample_users)
    logger.info(f"After randomly removing users - round {r}: {num_users=}")
    if num_users > args.sample_users * (1 + buffer_perc):
        logger.info(
            f"Number of users {num_users} are still greater than expected, keep removing..."
        )
        sample_df = new_sample_df.copy()
    else:
        logger.info(
            f"Number of users {num_users} are falling below expected threshold, stop and use `sample_df` as final output..."
        )
        keep_random_removing = False

    r += 1

Randomly removing 7248 users - Round 1 started
2025-01-08 00:27:45.790 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:27:48.109 | INFO     | __main__:<module>:27 - len(uu)=279691
2025-01-08 00:27:49.043 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6996610
2025-01-08 00:27:50.961 | INFO     | __main__:<module>:36 - len(ui)=19700
2025-01-08 00:27:51.407 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6931821
2025-01-08 00:27:51.532 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:27:53.354 | INFO     | __main__:<module>:27 - len(uu)=1983
2025-01-08 00:27:53.970 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6924220
2025-01-08 00:27:55.785 | INFO     | __main__:<module>:36 - len(ui)=47
2025-01-08 00:27:56.237 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6923805
2025-01-08 00:27:56.359 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:27:58.076 | INFO     | __main__:<module>:27 - len(uu)=17
2025-01-08 00:27:58.692 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6923739
2025-01-08 00:28:00.582 | INFO     | __main__:<module>:36 - len(ui)=1
2025-01-08 00:28:00.930 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6923730
2025-01-08 00:28:01.049 | INFO     | __main__:<module>:23 - Sampling round 4 started
2025-01-08 00:28:02.773 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:28:02.890 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:28:04.206 | INFO     | __main__:<module>:48 - After randomly removing users - round 1: num_users=724875
2025-01-08 00:28:04.206 | INFO     | __main__:<module>:50 - Number of users 724875 are still greater than expected, keep removing...


Randomly removing 4359 users - Round 2 started
2025-01-08 00:28:07.257 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:28:08.954 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:28:09.068 | INFO     | __main__:<module>:36 - len(ui)=82
2025-01-08 00:28:09.503 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6853500
2025-01-08 00:28:09.619 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:28:11.343 | INFO     | __main__:<module>:27 - len(uu)=22
2025-01-08 00:28:12.054 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6853412
2025-01-08 00:28:14.022 | INFO     | __main__:<module>:36 - len(ui)=2
2025-01-08 00:28:14.437 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6853396
2025-01-08 00:28:14.563 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:28:16.289 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:28:16.403 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:28:17.538 | INFO     | __main__:<module>:48 - After randomly removing users - round 2: num_users=435936
2025-01-08 00:28:17.538 | INFO     | __main__:<module>:50 - Number of users 435936 are still greater than expected, keep removing...


Randomly removing 4315 users - Round 3 started
2025-01-08 00:28:20.560 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:28:22.284 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:28:22.402 | INFO     | __main__:<module>:36 - len(ui)=54
2025-01-08 00:28:22.806 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6782665
2025-01-08 00:28:22.928 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:28:24.654 | INFO     | __main__:<module>:27 - len(uu)=15
2025-01-08 00:28:25.253 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6782606
2025-01-08 00:28:27.118 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:28:27.118 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:28:28.811 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:28:28.932 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:28:30.057 | INFO     | __main__:<module>:48 - After randomly removing users - round 3: num_users=431555
2025-01-08 00:28:30.057 | INFO     | __main__:<module>:50 - Number of users 431555 are still greater than expected, keep removing...


Randomly removing 4272 users - Round 4 started
2025-01-08 00:28:33.160 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:28:34.837 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:28:34.955 | INFO     | __main__:<module>:36 - len(ui)=62
2025-01-08 00:28:35.383 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6713058
2025-01-08 00:28:35.504 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:28:37.219 | INFO     | __main__:<module>:27 - len(uu)=21
2025-01-08 00:28:37.874 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6712975
2025-01-08 00:28:39.655 | INFO     | __main__:<module>:36 - len(ui)=1
2025-01-08 00:28:40.012 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6712966
2025-01-08 00:28:40.134 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:28:41.851 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:28:41.968 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:28:43.078 | INFO     | __main__:<module>:48 - After randomly removing users - round 4: num_users=427225
2025-01-08 00:28:43.078 | INFO     | __main__:<module>:50 - Number of users 427225 are still greater than expected, keep removing...


Randomly removing 4229 users - Round 5 started
2025-01-08 00:28:46.042 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:28:47.704 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:28:47.820 | INFO     | __main__:<module>:36 - len(ui)=71
2025-01-08 00:28:48.226 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6644650
2025-01-08 00:28:48.336 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:28:50.080 | INFO     | __main__:<module>:27 - len(uu)=23
2025-01-08 00:28:50.833 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6644558
2025-01-08 00:28:52.906 | INFO     | __main__:<module>:36 - len(ui)=1
2025-01-08 00:28:53.233 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6644549
2025-01-08 00:28:53.346 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:28:55.061 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:28:55.171 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:28:56.314 | INFO     | __main__:<module>:48 - After randomly removing users - round 5: num_users=422932
2025-01-08 00:28:56.314 | INFO     | __main__:<module>:50 - Number of users 422932 are still greater than expected, keep removing...


Randomly removing 4186 users - Round 6 started
2025-01-08 00:28:59.270 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:29:00.965 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:01.081 | INFO     | __main__:<module>:36 - len(ui)=67
2025-01-08 00:29:01.514 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6578228
2025-01-08 00:29:01.638 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:29:03.309 | INFO     | __main__:<module>:27 - len(uu)=24
2025-01-08 00:29:04.015 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6578136
2025-01-08 00:29:05.763 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:29:05.764 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:29:07.532 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:07.643 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:29:08.736 | INFO     | __main__:<module>:48 - After randomly removing users - round 6: num_users=418680
2025-01-08 00:29:08.736 | INFO     | __main__:<module>:50 - Number of users 418680 are still greater than expected, keep removing...


Randomly removing 4144 users - Round 7 started
2025-01-08 00:29:11.671 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:29:13.311 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:13.424 | INFO     | __main__:<module>:36 - len(ui)=74
2025-01-08 00:29:13.850 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6511236
2025-01-08 00:29:13.965 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:29:15.632 | INFO     | __main__:<module>:27 - len(uu)=21
2025-01-08 00:29:16.267 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6511153
2025-01-08 00:29:18.030 | INFO     | __main__:<module>:36 - len(ui)=1
2025-01-08 00:29:18.347 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6511144
2025-01-08 00:29:18.462 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:29:20.158 | INFO     | __main__:<module>:27 - len(uu)=1
2025-01-08 00:29:20.650 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6511140
2025-01-08 00:29:22.417 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:29:22.418 | INFO     | __main__:<module>:23 - Sampling round 4 started
2025-01-08 00:29:24.064 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:24.175 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:29:25.258 | INFO     | __main__:<module>:48 - After randomly removing users - round 7: num_users=414470
2025-01-08 00:29:25.258 | INFO     | __main__:<module>:50 - Number of users 414470 are still greater than expected, keep removing...


Randomly removing 4103 users - Round 8 started
2025-01-08 00:29:28.112 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:29:29.743 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:29.866 | INFO     | __main__:<module>:36 - len(ui)=61
2025-01-08 00:29:30.274 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6445394
2025-01-08 00:29:30.388 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:29:32.044 | INFO     | __main__:<module>:27 - len(uu)=14
2025-01-08 00:29:32.589 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6445338
2025-01-08 00:29:34.299 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:29:34.299 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:29:35.936 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:36.049 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:29:37.122 | INFO     | __main__:<module>:48 - After randomly removing users - round 8: num_users=410304
2025-01-08 00:29:37.122 | INFO     | __main__:<module>:50 - Number of users 410304 are still greater than expected, keep removing...


Randomly removing 4061 users - Round 9 started
2025-01-08 00:29:39.897 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:29:41.566 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:41.678 | INFO     | __main__:<module>:36 - len(ui)=69
2025-01-08 00:29:42.082 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6380044
2025-01-08 00:29:42.191 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:29:43.836 | INFO     | __main__:<module>:27 - len(uu)=26
2025-01-08 00:29:44.365 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6379941
2025-01-08 00:29:46.135 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:29:46.135 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:29:47.781 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:47.890 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:29:48.957 | INFO     | __main__:<module>:48 - After randomly removing users - round 9: num_users=406187
2025-01-08 00:29:48.957 | INFO     | __main__:<module>:50 - Number of users 406187 are still greater than expected, keep removing...


Randomly removing 4021 users - Round 10 started
2025-01-08 00:29:51.796 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:29:53.514 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:53.621 | INFO     | __main__:<module>:36 - len(ui)=79
2025-01-08 00:29:54.028 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6315557
2025-01-08 00:29:54.133 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:29:55.858 | INFO     | __main__:<module>:27 - len(uu)=22
2025-01-08 00:29:56.525 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6315471
2025-01-08 00:29:58.261 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:29:58.261 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:29:59.864 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:29:59.986 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:01.054 | INFO     | __main__:<module>:48 - After randomly removing users - round 10: num_users=402100
2025-01-08 00:30:01.054 | INFO     | __main__:<module>:50 - Number of users 402100 are still greater than expected, keep removing...


Randomly removing 3980 users - Round 11 started
2025-01-08 00:30:03.823 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:30:05.430 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:30:05.541 | INFO     | __main__:<module>:36 - len(ui)=61
2025-01-08 00:30:05.926 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6252694
2025-01-08 00:30:06.033 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:30:07.657 | INFO     | __main__:<module>:27 - len(uu)=19
2025-01-08 00:30:08.239 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6252621
2025-01-08 00:30:09.953 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:09.953 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:30:11.551 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:30:11.671 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:12.672 | INFO     | __main__:<module>:48 - After randomly removing users - round 11: num_users=398057
2025-01-08 00:30:12.672 | INFO     | __main__:<module>:50 - Number of users 398057 are still greater than expected, keep removing...


Randomly removing 3940 users - Round 12 started
2025-01-08 00:30:15.426 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:30:17.032 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:30:17.144 | INFO     | __main__:<module>:36 - len(ui)=79
2025-01-08 00:30:17.549 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6190162
2025-01-08 00:30:17.655 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:30:19.260 | INFO     | __main__:<module>:27 - len(uu)=23
2025-01-08 00:30:19.928 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6190071
2025-01-08 00:30:21.646 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:21.646 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:30:23.249 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:30:23.359 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:24.359 | INFO     | __main__:<module>:48 - After randomly removing users - round 12: num_users=394058
2025-01-08 00:30:24.360 | INFO     | __main__:<module>:50 - Number of users 394058 are still greater than expected, keep removing...


Randomly removing 3900 users - Round 13 started
2025-01-08 00:30:27.084 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:30:28.657 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:30:28.772 | INFO     | __main__:<module>:36 - len(ui)=70
2025-01-08 00:30:29.155 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6126872
2025-01-08 00:30:29.259 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:30:30.862 | INFO     | __main__:<module>:27 - len(uu)=15
2025-01-08 00:30:31.389 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6126814
2025-01-08 00:30:33.073 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:33.073 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:30:34.685 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:30:34.799 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:35.802 | INFO     | __main__:<module>:48 - After randomly removing users - round 13: num_users=390095
2025-01-08 00:30:35.803 | INFO     | __main__:<module>:50 - Number of users 390095 are still greater than expected, keep removing...


Randomly removing 3861 users - Round 14 started
2025-01-08 00:30:38.477 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:30:40.048 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:30:40.156 | INFO     | __main__:<module>:36 - len(ui)=73
2025-01-08 00:30:40.545 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6064538
2025-01-08 00:30:40.648 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:30:42.237 | INFO     | __main__:<module>:27 - len(uu)=27
2025-01-08 00:30:42.742 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6064430
2025-01-08 00:30:44.426 | INFO     | __main__:<module>:36 - len(ui)=2
2025-01-08 00:30:44.770 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6064412
2025-01-08 00:30:44.871 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:30:46.373 | INFO     | __main__:<module>:27 - len(uu)=1
2025-01-08 00:30:46.826 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6064408
2025-01-08 00:30:48.501 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:48.501 | INFO     | __main__:<module>:23 - Sampling round 4 started
2025-01-08 00:30:50.041 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:30:50.148 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:51.150 | INFO     | __main__:<module>:48 - After randomly removing users - round 14: num_users=386180
2025-01-08 00:30:51.151 | INFO     | __main__:<module>:50 - Number of users 386180 are still greater than expected, keep removing...


Randomly removing 3822 users - Round 15 started
2025-01-08 00:30:53.872 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:30:55.425 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:30:55.531 | INFO     | __main__:<module>:36 - len(ui)=73
2025-01-08 00:30:55.919 | INFO     | __main__:<module>:40 - After removing ui: len(new_sample_df)=6003925
2025-01-08 00:30:56.023 | INFO     | __main__:<module>:23 - Sampling round 2 started
2025-01-08 00:30:57.563 | INFO     | __main__:<module>:27 - len(uu)=20
2025-01-08 00:30:58.132 | INFO     | __main__:<module>:31 - After removing uu: len(new_sample_df)=6003846
2025-01-08 00:30:59.767 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:30:59.767 | INFO     | __main__:<module>:23 - Sampling round 3 started
2025-01-08 00:31:01.322 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:31:01.426 | INFO     | __main__:<module>:36 - len(ui)=0
2025-01-08 00:31:02.419 | INFO     | __main__:<module>:48 - After randomly removing users - round 15: num_users=382291
2025-01-08 00:31:02.419 | INFO     | __main__:<module>:50 - Number of users 382291 are still greater than expected, keep removing...


Randomly removing 3784 users - Round 16 started
2025-01-08 00:31:05.041 | INFO     | __main__:<module>:23 - Sampling round 1 started
2025-01-08 00:31:06.526 | INFO     | __main__:<module>:27 - len(uu)=0
2025-01-08 00:31:06.610 | INFO     | __main__:<module>:36 - len(ui)=75

In [17]:
px.histogram(new_sample_df.groupby(args.user_col).size())

In [18]:
px.histogram(new_sample_df.groupby(args.item_col).size())

In [19]:
new_sample_df.to_parquet(f"{args.notebook_persist_dp}/full_data.parquet")

### Read data and split it into train-val-test sets

In [10]:
new_sample_df = pd.read_parquet(f"{args.notebook_persist_dp}/full_data.parquet")

In [11]:
train_df, val_df, test_df = train_test_split_timebased(new_sample_df, args, timestamp_col= "event_timestamp")

2025-01-21 15:28:05.146 | INFO     | src.utils.split_time_based:train_test_split_timebased:25 - Removing users from val and test sets...
2025-01-21 15:28:05.148 | INFO     | src.utils.split_time_based:train_test_split_timebased:36 - Removed 16 users from val set
2025-01-21 15:28:05.148 | INFO     | src.utils.split_time_based:train_test_split_timebased:39 - Removed 28 users from test set
2025-01-21 15:28:05.148 | INFO     | src.utils.split_time_based:train_test_split_timebased:42 - Train set has 1096 users
2025-01-21 15:28:05.148 | INFO     | src.utils.split_time_based:train_test_split_timebased:43 - Val set has 218 users
2025-01-21 15:28:05.148 | INFO     | src.utils.split_time_based:train_test_split_timebased:44 - Test set has 188 users

In [12]:
def plot_interactions_over_time(df):
    plot_df = df.groupby("event_timestamp").size()

    fig = px.line(
        x=plot_df.index,
        y=plot_df.values,
        labels={"x": "Date", "y": "Number of Interactions"},
        title="Interaction over time",
        height=500,
    )

    fig.update_layout(yaxis=dict(showticklabels=True, tickformat=","))

    fig.show()

In [13]:
plot_interactions_over_time(train_df)

In [14]:
plot_interactions_over_time(val_df)

In [15]:
# Persist the data
train_df.to_parquet(f"{args.notebook_persist_dp}/train.parquet")
val_df.to_parquet(f"{args.notebook_persist_dp}/val.parquet")
test_df.to_parquet(f"{args.notebook_persist_dp}/test.parquet")